In [8]:
import numpy as np
import torch
batch_size = 24
lv_dim = 6
length = batch_size // lv_dim
data = []
for i in range(batch_size* length):
    tmp = []
    for j in range(lv_dim):
        tmp.append(i*lv_dim + j)
    data.append(tmp)
lv = torch.from_numpy(np.array(data))
print("originshape:")
print(lv)

print("squeeze shape:")
lv_1 = lv.view(-1, length, lv_dim)
print(lv_1)

print("squeeze shape 2:")
lv_2 = lv.view(-1, length * lv_dim)
print(lv_2)

originshape:
tensor([[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137],
        [138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147

In [13]:
bs, v_dim = lv_2.shape
print(lv.shape, lv_1.shape, lv_2.shape)
print(lv.view(-1, 24))

torch.Size([96, 6]) torch.Size([24, 4, 6]) torch.Size([24, 24])
tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
          38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
          62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
          86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133,
         134, 135, 136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
         158, 159, 160,

In [9]:
batch_size = 24
lv_dim = 6
length = batch_size // lv_dim
data = []
for i in range(batch_size* length):
    tmp = []
    for j in range(lv_dim):
        tmp.append(i*lv_dim + j)
    data.append(tmp)
lv = torch.from_numpy(np.array(data))
print("originshape:")
print(lv)

print("squeeze shape:")
lv_1 = lv.reshape(-1, length, lv_dim)
print(lv_1)

print("squeeze shape 2:")
lv_2 = lv.reshape(-1, length * lv_dim)
print(lv_2)

originshape:
tensor([[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131],
        [132, 133, 134, 135, 136, 137],
        [138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147

# GNN GCN Convolutional

### CiteSeer数据集
- print(dataset.num_node_features, dataset.num_classes)
    有6个类别， 3327个节点，3703维度特征，9104//2=4557条边
- print(len(dataset), '\n', dataset[0], '\n', dataset[0].is_directed())
    Data(x=[3327, 3703], edge_index=[2, 9104], y=[3327], train_mask=[3327], val_mask=[3327], test_mask=[3327]),
    无向图
- dataset[0].x.shape, dataset[0].edge_index.shape
    torch.Size([3327, 3703]) torch.Size([2, 9104])
- ende

In [15]:
import random
import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.datasets import Planetoid
from torch_geometric.nn import GCNConv
from torch_geometric.transforms import NormalizeFeatures
from torch_geometric.utils import to_undirected

class GCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        # x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

NameError: name 'dataset' is not defined

In [ ]:
dataset = Planetoid(root='C:/data/CiteSeer', name='CiteSeer', transform=NormalizeFeatures())
print(len(dataset), '\n', dataset[0], '\n', dataset[0].is_directed())
print(dataset.num_node_features, dataset.num_classes)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
data = dataset[0].to(device)
print(data)
print(data.x.shape, data.edge_index.shape)

gcn_model = GCN(dataset.num_node_features, 32, dataset.num_classes).to(device)
print(gcn_model)

print(dataset.num_features, dataset.num_classes)
print(data.x.shape)
print(data.edge_index)
print(dataset.y)

# 探索完毕，尝试用我所需的数据形式输入到这个GNN GCN里面测试
## My Data

In [ ]:
# ======build data==============
# data = Planetoid(root='/data/CiteSeer', name='CiteSeer')
class_num = 5
# cough, wheeze, inhalation, exhalation, vomit, whooping; sniff; clearthroat, hum, speech
event_num = 6
node_num = 64
node_dim = 16
batch_size = 128
features = torch.rand(size=(node_num, node_dim))
print(features.size(0), features.size(1))
# 示例边索引 (无向图边: 0-1, 1-2, 2-3, 3-0)
edge_index = [[], []]
for i in range(96):
    st = random.randint(0, node_num-1)
    en = random.randint(0, node_num-1)
    edge_index[0].append(st)
    edge_index[1].append(en)
    edge_index[0].append(en)
    edge_index[1].append(st)
edge_index = torch.from_numpy(np.array(edge_index))
edge_index = to_undirected(edge_index, num_nodes=features.size(0))
print(edge_index)

class GCN(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(in_channels, hidden_channels)
        self.conv2 = GCNConv(hidden_channels, out_channels)

    def forward(self, x, edge_index):
        # x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
gcn_model = GCN(in_channels=node_dim, hidden_channels=32, out_channels=class_num).to(device)
print(gcn_model)

# 创建图数据对象
graph = Data(x=features, edge_index=edge_index)
print(graph)

graph=graph.to(device)
gcn_model(x=graph.x, edge_index=graph.edge_index)

# End